### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by MichaHoffmann** [mitchellh/tree-sitter-hcl#2]
Hey, 

about 3 weeks ago i started to write a tree-sitter grammar for hcl too: https://github.com/MichaHoffmann/tree-sitter-hcl 

it works reasonably well and handles templates ( somewhat ). would you like to collaborate here ? If so i would try to help out here and deprecate mine.

i hope its not bad form to advertise here, but i could not reach you otherwise.

**Comment by mitchellh** [comment]
Thanks for doing this! I'm going to mark yours as the more feature complete one and note it in the README. I never wanted to maintain this :)

**Comment by MichaHoffmann** [comment]
Oh wow, thank you.
